[Greeter]
background=/usr/share/backgrounds/ageless/ageless-default.png
background-color=#16161a
theme-name=Arc-Dark
icon-theme-name=Mint-Y-Sand
font-name=Noto Sans 11
logo=/usr/share/ageless/logo/ageless-logo-64.png
draw-user-backgrounds=false
draw-grid=false
show-hostname=true
